version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "443:443"
      - "1337:1337"
    container_name: rtmp_server
    volumes:
      - ./hls:/tmp/hls
      - ./recordings:/tmp/recordings

  auth:
    build: ./auth
    container_name: auth_server
    volumes:
      - ./hls:/tmp/hls
      - ./recordings:/tmp/recordings
